### ISSUE TITLE
DDE is launching with wallpaper only

### ISSUE THREAD

**Issue by cmonty14** [sparkylinux/sparky-desktop-meta#1]
Hello!
I have installed DDE from repo "sparky-dde.list".

The installation finished w/o errors.
However, after reboot and starting display manager I can logon but there's no start menu loaded; there's only the background.

`Nov 19 18:50:24 pc8-nb com.deepin.dde.Dock[925]: /usr/bin/dde-dock: relocation error: /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2: symbol _ZN27QPlatformIntegrationFactory4keysERK7QString, version Qt_5 not defined in file libQt5Gui.so.5 with link time reference
Nov 19 18:50:24 pc8-nb daemon/watchdog[901]: manager.go:76: Launch 'dde-dock' failed: org.freedesktop.DBus.Error.Spawn.ChildExited:Process com.deepin.dde.Dock exited with status 127`

`Nov 19 18:50:24 pc8-nb com.deepin.dde.desktop[925]: /usr/bin/dde-desktop: relocation error: /usr/lib/x86_64-linux-gnu/libdde-file-manager.so.1: symbol _ZN25QPlatformFileDialogHelper12filterRegExpE, version Qt_5 not defined in file libQt5Gui.so.5 with link time reference
Nov 19 18:50:24 pc8-nb daemon/watchdog[901]: manager.go:76: Launch 'dde-desktop' failed: org.freedesktop.DBus.Error.Spawn.ChildExited:Process com.deepin.dde.desktop exited with status 127`

**Comment by pavroo** [comment]
The problem is that the dde devs don't share any config for other devs.
I will try to find missing libs, but if no luck I consider to remove the desktop from Sparky repos.

**Comment by cmonty14** [comment]
Hm... what exactly do you request from DDE devs?

**Comment by pavroo** [comment]
Some basic informations about building process and deps, common deps, etc.
Having that I could build the desktop myself, like a few other ones.

**Comment by cmonty14** [comment]
Hm... I think you can find all packages and build dependencies [here](https://www.deepin.org/en/dde/):
https://github.com/linuxdeepin/dde-desktop
https://github.com/linuxdeepin/dde-file-manager
https://github.com/linuxdeepin/dde-control-center
https://github.com/linuxdeepin/dde-launcher
https://github.com/linuxdeepin/dde-dock
https://github.com/linuxdeepin/deepin-wm

**Comment by pavroo** [comment]
Looks like the the dde applications have been compiled with different version of Qt then Debian have, and they don't want to start.
A solution is to build the packages with present verision of Qt or wait for deepin devs to do so.
I don't have so much time to compile so many dde related packages, so in my way, if something doesn't work shoudn't be kept in repos.

**Comment by cmonty14** [comment]
Hm... I question why DDE developers should provide their packages compiled with another Qt version.
They provide their source code on github that anybody can download and compile.

**Comment by cmonty14** [comment]
Can you confirm that DDE is dead on Sparky as of now?

**Comment by pavroo** [comment]
Yes, it is, I mentioned about that already:
https://sparkylinux.org/sparky-news-2017-12-30/
